#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH

build() {
    root=$PWD
    rm -rf dist
    cp -rf src dist && /usr/bin/find dist -name '*.spec.ts' | xargs rm -f
    cd dist
    tsc --project $root --target es2015 --module commonjs --sourceMap true --skipLibCheck true --declaration true
    cd ..
    cp README.md LICENSE package.json dist
}

eslint_run() {
    eslint src --ext ts
}

"$@"
